//
//  HelloPresenter.swift
//  MeetupMovile
//
//  Created by Yasmin Benatti on 2018-10-15.
//  Copyright (c) 2018 Yasmin Benatti. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol HelloPresentationLogic {
    func presentSuccess(response: Hello.Something.Response)
    func presentError(errorResponse: Hello.Something.ErrorResponse)
}

class HelloPresenter: HelloPresentationLogic {
    weak var viewController: HelloDisplayLogic?
    
    // MARK: Do something
    
    func presentSuccess(response: Hello.Something.Response) {
        let viewModel = Hello.Something.ViewModel(fullName: response.firstName + response.lastName)
        viewController?.displaySuccess(viewModel: viewModel)
    }
    
    func presentError(errorResponse: Hello.Something.ErrorResponse) {
        viewController?.displayError(errorResponse: errorResponse)
    }
}
