//
//  HelloInteractor.swift
//  MeetupMovile
//
//  Created by Yasmin Benatti on 2018-10-15.
//  Copyright (c) 2018 Yasmin Benatti. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol HelloInteractorInput {
    func doSomething(request: Hello.Something.Request)
}

protocol HelloDataStore {
    //var name: String { get set }
}

class HelloInteractor: HelloInteractorInput, HelloDataStore {
    var presenter: HelloPresenterInput?
    var worker: HelloWorker?
    let apiClient: APIClientProtocol
    
    init(apiClient: APIClientProtocol) {
        self.apiClient = apiClient
    }
    
    // MARK: Do something
    
    func doSomething(request: Hello.Something.Request) {
        worker = HelloWorker(apiClient: apiClient)
        worker?.doSomeWork(successHandler: { [weak self] (firstName, lastName) in
            let response = Hello.Something.Response(firstName: firstName, lastName: lastName)
            self?.presenter?.presentSuccess(response: response)
        }, failureHandler: { [weak self] error in
            let errorResponse = Hello.Something.ErrorResponse(error: error)
            self?.presenter?.presentError(errorResponse: errorResponse)
        })
    }
}
