//
//  HelloModels.swift
//  MeetupMovile
//
//  Created by Yasmin Benatti on 2018-10-15.
//  Copyright (c) 2018 Yasmin Benatti. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Hello {
    // MARK: Use cases
    
    enum Something {
        struct Request {
        }
        struct Response {
            let firstName: String
            let lastName: String
        }
        struct ErrorResponse {
            let error: Error?
        }
        struct ViewModel {
            let fullName: String
        }
    }
}
