//
//  HelloPresenterTests.swift
//  MeetupMovile
//
//  Created by Yasmin Benatti on 16/10/18.
//  Copyright (c) 2018 Yasmin Benatti. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import MeetupMovile
import XCTest
import Nimble

class HelloPresenterTests: XCTestCase {
    // MARK: Subject under test
    
    var sut: HelloPresenter!
    
    // MARK: Test lifecycle
    
    override func setUp() {
        super.setUp()
        setupHelloPresenter()
    }
    
    override func tearDown() {
        super.tearDown()
    }
    
    // MARK: Test setup
    
    func setupHelloPresenter() {
        sut = HelloPresenter()
    }
    
    // MARK: Test doubles
    
    class HelloViewControllerInputSpy: HelloViewControllerInput {
        var displaySuccessCalled = false
        var displayErrorCalled = false
        
        func displaySuccess(viewModel: Hello.Something.ViewModel) {
            displaySuccessCalled = true
        }
        
        func displayError(errorResponse: Hello.Something.ErrorResponse) {
            displayErrorCalled = true
        }
    }
    
    // MARK: Tests
    
    func testPresentSomething() {
        // Given
        let spy = HelloViewControllerInputSpy()
        sut.viewController = spy
        let response = Hello.Something.Response(firstName: "Yasmin", lastName: "Benatti")
        
        // When
        sut.presentSuccess(response: response)
        
        // Then
        
        // Nimble
        expect(spy.displaySuccessCalled).to(beTrue())
    }
}
