//
//  HelloWorkerTests.swift
//  MeetupMovile
//
//  Created by Yasmin Benatti on 16/10/18.
//  Copyright (c) 2018 Yasmin Benatti. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import MeetupMovile
import XCTest

class HelloWorkerTests: XCTestCase {
  // MARK: Subject under test
  
  var sut: HelloWorker!
  
  // MARK: Test lifecycle
  
  override func setUp() {
    super.setUp()
    setupHelloWorker()
  }
  
  override func tearDown() {
    super.tearDown()
  }
  
  // MARK: Test setup
  
  func setupHelloWorker() {
    sut = HelloWorker(apiClient: APIClientMock())
  }
    
  // MARK: Tests
  
  func testSomething() {
    // Given
    
    // When
    
    // Then
  }
}
